version: '3'

services:
  jupyterlab:
    build: .
    command: bash -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root"
    ports:
      - "8888:8888"
    volumes:
    - ./notebooks:/opt/app/data